name: valgrind

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install_valgrind
        run: sudo apt install -y valgrind
      - name: cmake
        run: cmake -S .
      - name: make
        run: make
      - name: make memcheck
        run: make valgrind
